# Sadece Python kullan, default venv'li install'Ä± kullan
providers = ["python"]

[phases.setup]
  nixPkgs = ["python312", "python312Packages.pip", "gcc"]

[start]
  cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
